### ISSUE TITLE
building the docker image doesn't work

### ISSUE THREAD

**Issue by ilbambino** [honeycombio/logspout-honeycomb#6]
if you the `make docker` it fails.

There are two issues with it:

go 1.7+ is needed because you use the `context` package, and alpine 3.4 only has 1.6. I changed the base image from `gliderlabs/alpine:3.4` to the official `alpine:3.5` and now it goes on.

There is the bug https://github.com/niemeyer/gopkg/issues/50 with _gopkg.in_ and doing a `go get` fails because of the 301. So I added `git config --global http.https://gopkg.in.followRedirects true` in `build.sh` before the `go get`. And now I can build the image. I could make a pull req. but it is so easy that I leave it here 😄 

btw, why don't you provide an image already built in docker hub?

**Comment by emfree** [comment]
Thanks for the report! Fixed, and we now have an image available: https://hub.docker.com/r/honeycombio/logspout-honeycomb/ :)

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.
